experiment_name: "navigation"
env_name: "navigation-v0"

log_dir: "~/meta_critics/logs"
model_dir: "~/meta_critics/models/navigation"
create_dir: True

env-args:
  low: -0.5
  high: 0.5

trajectory_sampler:
  remap_types: True

trainer:
  type: distributed_rpc
  use_discount_gamma: True
  gae_lambda_factor: 1.0
  gamma_factor: 0.99
  meta_test_freq: 20
  save_freq: 20
  use_gae: True
  resume: True
  num-workers: 1

# Policy network
policy_network:
  hidden_sizes: [64, 64]
  activation: "tanh"

meta_task:
  num_batches: 500       # outer-loop updates
  num_meta_task: 40      # number of task
  num_trajectory: 20     # Number of trajectories to sample for each task.
  num_steps: 1           # Number of gradient steps in the inner loop / fast adaptation.
  fast_lr: 0.1           # Step size for each gradient step in the inner loop / fast adaptation.
  first_order: false

model:
  name: trpo
  model_type: AsyncMAMLTRPO  # model type.
  max_kl: 1.0e-2             # size of the trust-region
  cg_iters: 10               # Number of iterations of Conjugate Gradient.
  cg_damping: 1.0e-5         # Value of the damping in Conjugate Gradient.
  ls_max_steps: 15           # Maximum number of steps in the line search.
  ls_backtrack_ratio: 0.8    # Ratio to use for