experiment_name: "antdir"
env_name: "AntPos-v4"

env-args:
  low: -3.0
  high: 3.0
  normalization_scale: 10.0
  max_episode_steps: 100

wandb:
  entity: spyroot
  project: dh-maml

model_root: "models"  # a root dir so all folder will be under.
log_dir: "~/meta_critics/logs/antgoal"
model_dir: "~/meta_critics/models/antgoal"
create_dir: True

trainer:
  use_wandb: True
  type: distributed_rpc
  save_freq: 20
  meta_test_freq: 20
  use_gae: True
  gamma_factor: 0.99
  gae_lambda_factor: 1.0
  use_discount_gamma: True
  resume: True
  num-workers: 1

# Policy network
policy_network:
  hidden_sizes: [64, 64]
  activation: "tanh"

trajectory_sampler:
  remap_types: False


meta_task:
  num_meta_task: 40     # number of meta task in batch
  num_trajectory: 20   # Number of trajectories to sample for each task.
  num_steps: 1          # Number of gradient steps in the inner loop / fast adaptation.
  fast_lr: 0.1          # Step size for each gradient step in the inner loop / fast adaptation.
  num_batches: 500      # outer-loop updates
  first_order: false

model:
  name: trpo
  model_type: ConcurrentMamlTRPO  # model type.
  max_kl: 1.0e-2             # trpo max kl term
  cg_iters: 10               # Number of iterations of Conjugate Gradient.
  cg_damping: 1.0e-5         # Value of the damping in Conjugate Gradient.
  ls_max_steps: 15           # Maximum number of steps in the line search.
  ls_backtrack_ratio: 0.8    # Ratio to use for